### ISSUE TITLE
HTML error when parsing Agoda

### ISSUE THREAD

**Issue by YorickPeterse** [YorickPeterse/oga#119]
Somewhere on pages such as http://www.agoda.com/patong-resort-hotel/hotel/phuket-th.html there's a lump of HTML triggering the following error:

```
/home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/parser.rb:275:in `parser_error': Unexpected T_STRING_SQUOTE, expected element closing tag instead on line 3280 (LL::ParserError)
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/parser.rb:248:in `block in each_token'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:263:in `call'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:263:in `add_token'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:279:in `on_string_squote'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:204:in `advance_native'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:204:in `block in advance'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:147:in `read_data'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/lexer.rb:203:in `advance'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/parser.rb:245:in `each_token'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/parser.rb:282:in `parse'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/xml/parser.rb:282:in `parse'
        from /home/yorickpeterse/.gem/ruby/2.2.0/gems/oga-1.0.3/lib/oga/oga.rb:27:in `parse_html'
        from /tmp/blegh.rb:6:in `<main>'
```

Script to reproduce:

```ruby
require 'httpclient'
require 'oga'

body = HTTPClient.get('http://www.agoda.com/patong-resort-hotel/hotel/phuket-th.html').body

Oga.parse_html(body)
```

**Comment by YorickPeterse** [comment]
The following snippet seems to be the culprit:

```
<a id='ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar_div_triggername' class='iconquestion' onmouseover=ShowContentMouseOver('ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar_div_mouseover',0,'//cdn3.agoda.net/images/default/icon_questionmark.png','imgIcon_ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar');document.getElementById('calloutctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar').style.display='block';document.getElementById('callout2ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar').style.display='block'; onmouseout=HideContentMouseOver('ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar_div_mouseover');document.getElementById('calloutctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar').style.display='none';document.getElementById('callout2ctl00_ctl00_MainContent_ContentMain_hotelSearchbox1_BestPriceGuaranteed2_StaticToolbar').style.display='none';>
```
