### ISSUE TITLE
#parse_html doesn't behave as expected when there are redirections for given URL

### ISSUE THREAD

**Issue by 0mega** [YorickPeterse/oga#139]
Hi,
I stumbled upon a strange error which only appears when you feed a URL which will have a redirect (301) to the `Oga#parse_html`method.
To reproduce, one can use this two URLs which point to the same resource on YouTube, but the one on `http` protocol redirects to the `https`.
https://www.youtube.com/watch?v=Y45Zq-yKpRw (direct link)
http://www.youtube.com/v/Y45Zq-yKpRw?version=3&autohide=1 (redirects to the first link)

If we parse html of the first link, it returns the expected output:
`Oga.parse_html(open("https://www.youtube.com/watch?v=Y45Zq-yKpRw", allow_redirections: :safe).read)`

Now if we make the same call with a URL that has a redirection, the parser returns an error:
```
Oga.parse_html(open("http://www.youtube.com/v/Y45Zq-yKpRw?version=3&autohide=1", allow_redirections: :safe).read)
ArgumentError: string contains null byte
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:204:in `advance_native'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:204:in `block in advance'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:147:in `read_data'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/lexer.rb:203:in `advance'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:245:in `each_token'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:282:in `parse'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/xml/parser.rb:282:in `parse'
	from /Users/joanaperrynava/.rvm/gems/ruby-2.1.2/gems/oga-1.2.3/lib/oga/oga.rb:27:in `parse_html'
	from (irb):18
	from /Users/joanaperrynava/.rvm/rubies/ruby-2.1.2/bin/irb:11:in `<main>'
```

**Comment by YorickPeterse** [comment]
This is unrelated to Oga itself. Using the [open_uri_redirections](https://github.com/open-uri-redirections/open_uri_redirections) Gem (which I assume is the one you're using, please mention this in the future) I get the following output:

```
$ ruby -r open_uri_redirections -e 'p open("http://www.youtube.com/v/Y45Zq-yKpRw?version=3&autohide=1", allow_redirections: :safe).read'
"CWS\x11\xC8$\x00\x00x\xDA\xED9kw\e\xC7u3\xFB\xC0\xEC\x02\x04\t\x80O\xF1!\x81\x14)\x92\xF2\x12\x04I\x91\x14)J\x11E\xF1i\x8A\xA0A\xC9\x96eC\xC0\x12X<\xE4\x05\x16\xDA]P\xA2\x1D'\x8A\x12\xC7\xEE\xCBM\xFA`\x9B\xA6i\x98>\xD2\xB4n\xEB\xB4i\xFAn\xDD\xA6\xAD\xF3\x95\x94\e\xFBcOsNs\xFA\x03\xFA\xA5\x9F\xD8;\xB3\v\x12\x94,\x9F\xA6\xED\x97\x9ES\x92\xB3wf\xEE\xCC\xBDw\xEEk\x1E\xBC\x8F\x84\x1F\"T\xFFM\x84\xEA0\xBA\x1A\x94\x11B\x9F\xE2\xFF]@h'\x84\x90\xAA\xEB\xC6\xBD\xA4\xA9\xDA\x85R\xCEBh\x04u\xED\x9CG\xA8P1u\x84\xF2\xB6]\xB6\xA6\x87\x87\v\x91m\xBBP\xCCE\xD2Fqx\xAB0\xFC\xE2\xB9\xF1[w\x87\xB6\x9F-\xC7\xEF\r\xE7\xEFf\xB4\xACZ\xD1\xED\xC8\x9Dr\x0E\xE6J\b\xA5M\x84\xD6V\xA1\xEE\x03\n@\xA5\xA4'Y\xD3\x0F\xCC*\xB6\x91/d4\x87\xCF\xB4\xC3\xA7x\xF7\xBF\xC4\xA9\xF8\x18\xA7F\x84\xB6\n\xDA\xBDd\xDA\xA8\x94l 86vn\xCA\xE9\xCE\e\x96\x9D\xD4\xD5R\xAE\xA2\xE64\xCA\x1F\xBA\xEB\x11\xD2@\x16\xAD\xB8\xA9e2Z\x06z\x9A\x11\xD2\xB5R\xCE\xCE'--m\x942t\xF1\x93\x93\x80\xB8\x8DQ6\xAB\xABT\ee]\xDD\xD6\xCCd\xB1P*$\xCB\xA6\x9135\xCBJn\xAA\xE6\xC5\xAC\xAA[\xDA\x19\xAD\xA4n\xEAZR\xADd\nF2\xADZ\xF6E\xDB\xAChgt-\xA7\xA6\xB7\x93e\x10\x03&ojyu\xAB`\x98\x0E\xAEd$3\x9A\xAD\xA5m \x93Ij\xF7m\xADd\x15\x8C\x92\xE5`-\xD0\r\x90O\x9AZ)\xA3\x99\x9A\xE9v\xEBF.Y\xB0\x93\x99\x82E\x05J\xDA\xA6\xA69\x88J!\t\xB8\x1C\x98\xCE\x95\xC8\xDE\x02\xACZ\xD0\xE9\xD4c2Z\xE5\xBCf\x16\xD2\xAA>\x96I\xA6\xF3\xA6Q\xD4\\\xBCU4\f\xD0\xC1\xC7\xAC\xCE]\xBC\x05\x93\x80Arl\"ZN\xDAFrr4Z>>BSM\x1D\xA4\xD2\x8A\xD0\xB6\xB5$(\xCBv\a\x94\xC0>\x96m\x94\x93[\xB00\xC3\xE9t\x9C\xC4\xB2t\xC7\t.A\xFD^\xF6\xC8\x03\xAC\x1A\x0F\xD8\xB6\xADa@n\x16J\xC3\x0E\xAB\xA1\xAD\xAC\xBE\x98\xBFi\x8F\xCF\r\xA7\xCBV\x84N\xEC\xDA\xF1\x82\ee\xCAw\x10\x1A\x9A:r\xAA\xFC\xDD\xFF\x96\xFBRZ\xA0\xFA\xFB\bE\xA1\x15\xA8\x86\as\eG\xDE \xF4m\xE5\xDC\x80Ah<B\a\xB6R_\x84\x15&\v0\xAA\x86>\xA0\xAE!tO\xB5\xD3\xF9\xE4}}\xF3\xE9\xAB\x04$]%\e9d\xD9&\r\xC6!\x168t\xC9\xEAxl{~+B)t\xED\xF4!d\x17l\x1D\x1C;nlj\xA6\x1D\xBEV\x80I\x95bx(\xBCR\xD1\vj)<g\x94\xA9\x96\x9B\xC0\xC1\v\x96}}\eZ\xCC\x93i\v\xFA\xBF\x8FPV\xBB_Fh\xEA\\t\"\x1A\x9DR\x00\x9E?75\xCE\xE0\xE4H\x94\xC2\xA9\xE8\x04\xEB\x9F\x1A\x19\x99`p4J\xF1#c\xD1\xB1\x11\n\xC7\xC7&X{\xFC\xDCy\a\x8E\x8F\xD3q#\x13\xD1\xD11\x06GF\x9D\xF6\xD8\xB9s\fN\x8ERz#\x93\xA3\x13\x0E\x9C\x8CNRx\x1E(18\x1Au\xE0\xB9s\xE7\x19\x9C87\xCA\xE0\xE4\x883\xEE\xFC\x14\xA375:F\xE7\x8FF\xA3\xA3Q'\xC3\xE8\x8E\xE9G'\xA0\x19>\x8CX\xCD4\r\x93\xC6F2k\xAAi\e\"\f\xACGM\x85\xDE\x97\xD1:\x86\f\xD8R\x0F\xDF\xF5dr]M\xBF\x02i\xC2\x8A\xA4s\xDB\x95\x8DutP\x7FJ\x04\xF4\xFA[\t\xDC\x8F\xDC\xBEdN76U\x1DA\x90\xD8\x86M\xF5YT\v%\xA4\ejfN/\x94Q\x9A}L\r\xBC\x7F\xBEX\xB6\xB7\xAF\x19\x90\x99\x18\xE6\xB0\xB6\nc5\x13\xA9\x99\xCC\x1C\xB8\xD4&0ENd\xDE\xB1\xD4r\x01<\v\xACl\xE5\x11M\bf\tX\xCD\xBB\x95\xE5\x12\xC0\xAC\x9A\xD6\xC0\xEB \xAE\xE9\f\xA4\x9A\xB9JQ+\xD9\x16\xCA\x96\x90\x06\xF1\t\x02e4\xF0\x1Ac\eUJT*\xC6\x16\x99Z\xD1\xD8\xD2\x8E\x84qt\xC3$\xC9\xA0\x82\xB5^\xDB\xA4\xA14\x8C \xBF\x14l\xE6\xA4\xD3\xAE\xAB\xA2\x1AOE\xD4\x17\x9D\xF8\x88e\x11\x8B>\x10\xDA^v; \"\x91U\xD9t\xBC\x17%\xE9\x0E2<\x8C\xAA\x01\x8Cf764{\xDD4\xCA\v,\xB7\xEEpHB\x9D\xA1\xD0\xD78\xF4.O\e\xB8\x93u\xBD\r\xC9\x01!\xFE\x04|\xDE\x04\v\xC5v\x04$ \x89[\x83\x06nu\x1A\xFC\xDB\x90\xCD1\xAA\xEBF\x8E\xE6o\xF1\x10\xA9\x92@\xA8Y\x01p\x14\x88\x8C\x9A'>\xB3C\x10\xA1\x14%r\x19Hp\xAD\xB4\xDBAJo\xD7Q2<\x90\x01=~\x84\x8E0\xF2\x1A\xFDz\x97W\xA9t'\x10\x9B\xE3c\x98:\x86\xF1\xB3o\xFD\x1AE\x7F\xDD\x95\x98\xEBF1F\xA2\xA1sGD\x84\x87\xAE\xB5\xA3&w\xBC\x89\x8F7\x11k\x82\xA0\xC2\x91\xE8\x81\xCE\xF8%G`\x82\x04\x8E\r\x99s\xFA\xE9@\xB6TGc\xC18\xED\xA0\xFC>FF)\xDE\x1A;ZW\xC8\x15u\x10M\xA0C\xBD\b\x0E*\xDE\xFAXO\xE3\x13=MG\xC4\xC0\n\xCD\"\xAA!\xDDrH\xDA_\xA3\xC8\xE6\xB5K5cZ\xA9\x11\xF9\xD6\x1D\x19Im\xCE\n\xAA\xFD\xF4{\"\x0EX\x81-Wp4\x02m\x91\x99\\\x94\xDA\x97C\xCC\x18^\xE4vt,\x87\x9C6\x9D\xDA\xEE\x8Cd39w\xA6\x87\r\xF4H\x9D\xCE\xC00\xA6l\xBB\x9Ed{\x92\xB2%L\xA8SO\xC1JO\x139\x1C\xAF\x1As\x11\x86\xC9\xCCO\xBA\xA1\xE6e\xB2\x10r\x00?9\xCA\xBD\x0FA\xAA\x12\x88 \xD7:\xA7C\xA3'\xCE&|\x85\x83\x1C@gIG\xB3\xC2l\x96\xF4\t\xB3j\xE4rLt\xDAU\xE5\xA1\xCF\xC10\x9F\xAB\xB2\xDEE\xC0\t>\xFA\x95\xFAX\xDD\xCB\xEA\xA7\x16\x1D\xB3p\x8C\bp\xE4\xD9T\x81\x93\x04j\xF0\x06g\x85\x9C\x80\x1D';s\xB1\x15\x8E\x8FW\xA1\xFA\xD6I\x88\xC6k\xD7g7\xE6\x92\xD7f\x97\xD7\x90\x9D/X\xD5\x94\xC9\x12$\vh\x1A\xC5\xADn\x80W=\x97c\xC2\xF2qJ\xE9\xBB\x94\xD2\"X\x92\x1E\xDB\xD04d!7\rm\e\x15\xBB\xB2\xA9Er\x86\x91\xD35\xC8\x92\x16KBg\xD1\xC66\x1C\xAC\x8A\b\x8Em\x15\xB3`o;{\xF4U\xC3a\xD9\n,%\xEC\xB2q\x00O\x1A\x00\xF4\xB0\x05\xC6\x8FE#4e\xE4A\xEE\xCF\xDA\x8C\x93\x94\x98\xC7.S\v\xB4#\xAAa\x8FC\x868Y\x83M\x94A\xF4\xAB\x81\x7F\xE3g\xD0\x1C%v\xCBKUC\t\xF1\xDCV\x03:\xF6\xF3\xAF^\x90:\xE9,\"\xE9\xAE)\tI\x116\x93\xFB\xDB\xC9\x8D{\xD9uZA\xEF5\xFD\xA8\x8D\xA6#HF\xA6Z\xD4FP\x00E\xE8\xF4\xEFCPl\x19\x85L\x1D\xDB \"\xDA\x16M\xFC\xE2<\x05\xDEy\xBA\xCB\xB1\xAAg\x83e]i\xA1Rb\xBB\x1D\xB9b\x18\xA0\xB3\x92'\xB6y\a\x0E\x9B>gr\xC5.\xE8\x96|e\xDB\xD6fMS\xDDvIZL\x9D~g\x87\x9A3`\xC3\xB9ow\x80\xCC\xAE\xE2#U;Te\x96\xAA2\xFB\x9D\xF9\xEE\xB1\xD4\xB3Q\x06kh\xBD\x9F0s\xBA:\xD3\xE3lEm\xB0\x1DV7:\xB6\x8CU8\xA1h%\xCD\xF4\e\xA5\xD9\xA3\x9D\xB2\xCE(9\xC2-\xC3\xC9\xD2\xE7l\x9B+\xD6l\xB9\xE01J\xB4\xAB\xC1(\x1D\xA3\xD2XC\xB6J\xC3\xA33\n\x81\x1A\xE9\x986\xBC\ejVs\xA8\xFB\xABl\x98Z\e\x8DR\\\xBB[\x81mu]\xA5\x06\x01r\xD6\xC9'v\xE5\r\xEA\x83\xDA\v\xA6Z.k\xE6\xF0\xE3\xC4\xA7?y\xBC\xC7a\xD7\xF1\xC4\xB4#\x99d*65\x98\xD5\xB2:\xBF8\xBB\x9A\\\xD9H.\xDCX\x9B\xBB\xBE\x1C[K\xAE\xCD^\x9B\xF7\xC4\xB5\xDC\xFC\xFD\xB2\xAF\xE6`!\x1F\x9E\x14\xA4\x9Cf?\xAF\xEA\x15\xAD\xD5\x82\v\xC5:8\xC8\v\x05;\x0FF\x89kY8!i\xA6\x17\b\xDB\x1A\x9B)\xA7\xF3Z\xFA\x955X\xA9\xCFRA\xA9\x85W\xC1IrA\x16[\ei\xB3P\xB6g\xD3i\xB8 \xF8\xABX6\xCB\v\x97\x03}\x81^82M\xBAQ\xCA\xD1>\xA6\xBE%\xB5\x94\x81[\x88@\xF1'\xC0)\xD5J.o\x1F\xF9\xAB\x8B\x966\xDC\x18\xC6g}5Q\xDC\xC8\xEA\xCB%\x16\xE1\x9A\xD3\xE7\xD5]\x17\xC8\x1A\xDE\xF2\xA1E|5\x87\xA8nvn\x19\x1EV3p.f'\xEB\xD9\x8D\xB1a8*N\foV\n:\x9C\xD7\x9B\x8E9\xEC\xB4\xEB\xB0\xC7;\xAF:\xD0\x89\e\x1A\r\xC0[3O\x1D\x1F\xC4\xECI\xCF\x95[\x9A3\xB0\xE3\x13\x88t\xD6F\xEE4[>\xC5\xD3\xA3\xBEf\xE2\x11\x1E\xA2\#@=\xB66\x00\x84\xE5\xB5\xE5\xEB\"\x8B\x95`\x9A\x86$\xA0\x0E\xD7_\xB7\x1C;\xD2\xA4\xB4\x1CK\xCE\xC7\xE3\xB1x\xA8\xAA\xCB#\\\xFD\xC6\xFC\xDC\x8D\xF8\xF2\xF5\x17\x9D\x11uV^55\x87\x91U7{\xF5jrnvu\xF5\xCA\xEC\xDC\xB3\xD2\xFC\xCD\xEB\xF3\xF1\xB5\xD9\xD5P|\xFE\xB9\e\xF3\e\xD7\x93\xEB\xB3q\xF0.\xE8\xDC\x90\x1D\xF1K\x9A\xED\xBD\x11_ucB\xA0\xD6\xF0\x1F\xE3\x885\x91-\xB1.\xEB\xE6 \xEAK$\xAD\e\x16\xD8\xD0\x9FqW\xCC\x98\v\x19\xD5V\xBDG,\xB0\"\xB2\x94O\xDC\xA56Z\x9A\xBB\xDC\xA3\xD8\x93\xA8\x87\xE7\vz&\x90W\xADc\xBA\"\x10\xFET\x80z@\xC4\xEE\x95\xE8\x11\x13\xAEE\xDB2\x93\x86\xDE~\xBC\x15K\x9BS\xCB6\xC8\xD1\xF0\x98\xFA\xFD\xC7,\x15|\xC2\xAE-\x1F\xEF\x0E\xC1\xDB/\xA9C\xAF\xCE\x0E\xDD\x8A\x0EM%#\xBD\x89gz\xEB]#\xBB\x01\x1F|\"\xF2\xC5\x82\xB5\xA6\xAE\x89\xECb\xE2q\x1E\x1ED\xC8\x02\xFAvsU_\xE1\x81\xC1\xF0kaS\x039Ka\xFEB\xF8u\xFF@\x15E1\x91-\xD5\f\x17\xD8\xE6\x10\xBE\x18\xCE\x18iv\a\x88\xB8\xD7\x0E]\xA3\xAD\x81~g@\xFF\xE0\x85\x93N-b\xD9\xDB\x90W\\\xC7\x84\x89\xFD%\xA3\xA4\xF5_8_E\x9B\xE9\x8B\xFDw cX,\xC6\xA7{\xA8i\xA6\xE9\x160\x9C\xB7\x8B\xBA2\xB3id\xB6/\xCD\xC0\r L\x87\xBE\xDC\xEFq.\x1C\xFE\x97\xFB/\xCD\f3dO\xFF\x85\x9ECqhO\x84f\xB7\x92c\xAD\x01\x87\xCF\xE0\x05\xEE\xF5A\x9A\x8E\xAE\x17\x8A`1\xA6\x85\xE5\xAB\"\xB3\xDB\xF0\x13\xBA\n\xD3\xAC\x11N;\xDA\xB6\xC2EU\xCF\x1AfQ\xCB\x84o^[\x9D\x0E\xE3\x01\x8F\x12\x8ED\"\x83\xEDO\x99h\e\xE1\x10|\x8CW\xC2j\x98&\xA50\\`\xB4\x88L]\x811\xF4\x98\x9A\x05W~\x89\x0E\xA6\xF2\xF0\x05pI\xB8TY\"\xDB\x16e\xCBVM&(\x97-\xC9\x87\xE9N(\xC1:\xB8\x97_\xC69bj\xA0\xCC\xB4\xC6\xFF\xF0\xC1\xB7p\xB8\x19V\xF5\\E\xD5\v\xD9\x02\xE4D\xF0\x02\x8B%Q\x90\x1EnB\x95\xB4\r\xFC\xD6*E\xB8\xA9\x8BE\xEAs\x83\xCB:}\x1F\xD2\xC3O\x11\xBEz\xB9\v\xF7s\xFD\x91\xC6'3\xA7\xF5X\x12s\xF7\xAEc\x03\xFD\xC7\x1E\xF5\x04\xFA\x1E\x12\xFDq\x1FC\xB8\xB4\xC9\xAD\xADry]d\xCF\x10R\xF5\xE9\xCE\xE3<\xD9E\x7F\xDC\x17;\xEF\xD1c\x9D\xC8\xDE\xEA\x1A\x98\x90Z&\x99a\xF9\xDD\xF2\x1F{\xB6\xE3J\xBA\xC7y\x85\xFB'\xEE\xFF_\xE1\xFE\xF7_\xE1\xEA\x8F\xBF}\xF2#\x93\x93\x9C\xA6K\xD5\xF7Q\xDE\xB2\xF4\x8B?\xEE\x93\x9C\xF3\xCE\xA5Zc\xF4\xC0'\xD079nh\xCA\xE3\xBC\xC6\x89\xEC\xD9\x00G}5\x0Fj\xDE\xA3\x874~<\x12\x95\xAAOh\xBE\x1A'\x92\x0F\x1F\xCF.\xFFO\xDF\xCED\xF6l\xD6\xF9I\xAFfR\xF5\xC1L\xAA\xBE\x97\t\xF4\xA9\xEC=\xFC\x7F\xFC\xA9L\xA0\xAFd\xFC\xD0\xE8\xC4\x89\xA7\xBE\x8F\xF1#\x91\xE8\xBF\xE0c\x89C\xA1\xA6S\xD2\xA6\x92\xD7\x95j\xF8+N\xF8+G\xD1\xAC<\x16\xC7\xCA\xB18V\x9C V\x8E\xBB\x9B\xA2\xE9\nx\x98\x02~\xA2P?Q\x1C'Q\x98\x93(5.\xA2\x1C\xB9\x88Ru\x0F\xE5\xD0%\x14fQ\xA5j4\x85\xDAJ\xA1KU\x9E\xBA\xCCp\vn\xE1[\xBC-u-\xF5-\x81\xB6PKg[w\xDB\xE9\xF6n\x11\xD1\xDF\xD6z\xE9B{\xA8}\xA6\xFDb\xFB\xA5\xF6O\xB5_n\x97[b-\x05\xE8\xEF\xA4\xD8\xF6\xD3\xED\xBF\x84\xC5z?\xAE\x17\e\x02$\x18jljni\x95\xEB|\xB8]\xEA\b\xC8\xADX\xAA\xEF\xC4\x81.\xA9\xC3{\xF2\x14C\xBD\x05\xB7P\x8Ep\x02\xE1D\x82\xE1\x0EI\b\x96\b\x96\t\xEF#\x82\x9F\x88\r\xC4\x13$\xA4\x91\x90&B\x9A\ti!\xA4\x95\x906BN\x10\xD2NH\a\x91\xBA\b9I\xC8)\"\x85\x89\xA7\x87\xE0^\xE2\xEB#\xF8\f\xC1\xFD\x04\x0F\x10<H\xF0Y\xE2{\x86`\x85\xE0!\x82#\xA4n\x98\xF8\xA2\x04\x8F\x10<J\xF0\x18\x11\xCE\x11<A\xF0$\xC1\xE7\t\x9E\x92\xA7q\a\x88s\x95\xE09\xC2\xCF\x13\xBC@\xB8E\x82\x97\b\xB7L\xF0\n\xC1\xCF\x92\xB6u\x82\x9F#8N\xF0\x06i\xB8.\xDF\xC0\xF2\xF30\xFE\x05\xF9&\x96_\xC2\xF2\x14\xD4_\x96\x13\xF0\xBDMp\x924<O\x1An\x90\x80J\x1A6IC\x9Ap\x19\xE2\xD1\x88'K<9r\xE2\x0E\xC1z\a\\\xBC\x8B$P\"\xB8B\xF8m\x82_%\xF85\x82?\x87I\xC7C(\x9F\a2_\x80\xF2\x06\x94/B\xFBM(\xA0\xAB\x8E\x9F\x80\xF2\x93\x98\x04~\x06\x13\xFEKX\xFE2(/\xF0\xF3X\x0E\xF3\xF2\x0E\x16\xE49A\xEE\xE2I\xF0+\x98\x04\x7F\x05\xCA\xAFB\xF95(\xBBP\xBE\x01\xE57\xA0\xFC\x16\x94oB\xF9\x16\x94\xDF\x85\xF2{P\xFE\x00\xCA\x15\x12\xFC6\x80?\x82\xF2\x1D(\xDF\x85\xF2'P\xFE\f\xCA_@\xF9+(\x7F\x03\xE5o\xA1|\x0F\xCA?@y\xB1\x8B\xDD\xDD\xE1:\x8E1\x878\xFAAO|x$\xE1\xBA:\x0E\v\xA2;\x82\xC7\x82\xE0A^\xEC\xF5\x1E\xDE\xFE=\xAC\xB0\xF7\x14\xB8\xC8\xD3Y\x82\xDBO\x10v\xA7\x12\x02\xFD\x82\x80\x9E\xF8\xE1\xB0$3\x1E\xAC\xC5{}\x12L\xF2\xD5QZ\xD8\x8F\x91\xB7\x1E#\xBE\x01#O\x00\xE8y\xBDA\x8C\xB8\x100i\xC4HjB\xA8\x19\xB5\xD0\x87-\x8C\xC46\"\xCB\xA8\x155\x9F\x90\xBD\xA8\x1D\xB7w\xA3\x0E\xD4Q\xF4 a\x16\x97\xE0\xFBU\x8C\r\x00_\xC3\xB8\f\xE0\xEB\x18\xDFe(\x13\xBE\xBF\x8E\xB1\x05\xE071\xB6\x01\x8C\xE3\n|\x7F\e\xE3-\x00\xBF\x83\xF1=\x00\xEF`|\x1F\xC0\xEFc\xBC\xCDf\xBD\n\xDFw1~\r\xC0\x1Fb\xFCi\x87\xFC\xEB\x00\xFE\x18\xE3\xCF\xB0\x11\x9F\x85\xEF\x9Fb\xFC\x00\x03\xFCs\fN\x01\xF0/1~H\xE1_c\xFCy\n\xDF\xC3\xE0 \x00\xFF\x0E\x83\x93\x00\xFC{\f\x8E\x02\xF0\x1F1~\x93\xC2\xF71\xAE\xF3wxp'\xEA\n\xCAM'C\xBC\xFFT\xD0\x13\b\aI\xB0\e\xF1\x1E\xD4\x13\xF4\xB5\x9C\x0Ez\x9B{CB}_P\n\x9DA`\x95~\xC4\x89h (6\x9C\xC0\x83\b\x8B\x88\xF7a/\x98\xA4\r\xB7\t\bw\xE2f\x01q]`\x1DI\xE6\xF7\xA2\x8B`\x0F\x9E\x93\xBD/\xEEE\xF7\x96Q\xEA\xAC2\x1E{\x063\xA0\xE0\xBD\xD4P6\x92\x1DVf\xDF9K\xFF\x93:\x98\xD1\xB12\x9D\x8Dn\xE5\x03{\xB4z%\e\xCD\xD7\xED)s{Y\x7F\xAC\x91K\r\xA5\xB8\xEC\xC8^6\x18\e\xE5\x12c+c\xE8\xC1\xD8\x0F\xC2P\x16\xE9{\x9A\xE0m\xF8*\xDE\x8B\xBEp\xF6\xC3\xA8\x86\xF7\x8Bx/\xD1\xBC\xD2\x8C\xF2M{\xD9\xA6\xEC9g^\x03\xCCs\x9A\xE3\xD9\x89\xBDl\xCBas2{\xBE\xA6\x99\x9DRV\xF7\xB2\xF55\xCDk{\xD9PMsm/\xDB\xEA4\x13\xD3{\xD9\xBA\x95i\x9C\x90\xFBWd\x1C\xBB\xC0\x05\x9A\x11\xDA\x8B>\x8A\xDEBg?:\e}\xA6\x88\x13\x90\xF3P\x97\xC4/\xE2\xE2\xE7@\xFD3\x17\xF1%\xF0T\xC4\v\xA0\x90\xB3\xA0\x90\x04\xD9_ 8\xFB)\x17^V\x9F\xEC\x82\x95\xC3\n\x05:\xA3y/\x9A\x98Mp.\xE6\xCA\x02\x87c\xB3\x18\x90\xA2@d\xEF\x03X~\xF8\x8D\xB4p\x03= \x1FR\xED\xBD\x98\x8D\x86n \xD4\x8B\xD2\xA2\xDBTn-\xCC\xE1\x87iO`\f!y\xD3\xB3)\x9E\x86\xF1\x80\xDB\x14`\xE8)\x84\\\xC2W7\xAB\x9Dj\xF4QM}\xD4#\x06\xDF?8\x90<\x92Hu1\xFF\x80|\xF4Av!$\"\xF4\xC1\xA3\xD8\x02\x15\xC4\xC3\x81\x94>\x90r\x11\x06\xC4\x16i\x17\xA1\xB6o\x87\xAE%%\xB5\xB0\x84C\x10p\xB0\x06^I\xAD\xF0\xAE\xF4\x12/z\e\xA6\xA9\xED>rl\xA7\xE1GEPo \xD4\x83P\xAAM\xC3:\xF4\xE8\\\xAC\x8B\v\x04\xA9z?\xA0\xEAM\vL\xBF]\x92\xB0\x88[{\af.r\xCB\xD4'W \xF6\x91,p^ow\xAA-\xB5\xB2\xAF\xDC\\x\x16\x87\xFC\x87K\xBB\xF20\x00\xE9#\xFC06@\x95\xEA\x05\xCEu=\x94sZ\xA8a\xAD\xE1\x0F\x8A|b\x942\xBE,\x83\xA5\x17\x11\xBF\x02.\x86V)\xF1k\x10\x14^\xAF\x0Fr\x94tz/\xAA\xA1\x14\x89\xA6\xD6\xA2\xA9X4\xB5\x1EM=\x17M\xF9\xE0\xEF&\xEAb?y/0\xA9\xE31/\xF8\xF7\xA2\xB7;R\x9DJ\xFE\n\xCEw@\xA7\x9F\x83\xCE\xE0^4\x15\xCF\x9E\xDC:\e\x82t5\x98:\xB3\xB3\x84P=\xCF\v\xF2$\x15\xE9\a\xD1Tw\x88\a\r\x9C\\J\xD114>\x12\x03\xCA+\v\x03xk)\x10\xA0\x9A\xD8\xA7\x9A\xF8\xD0U\x04\xD7\xBF\x84\e\xBA\xFBf6P\x83\bD\xE6\x80\xF8\xC9 ]\xEC\xD2~/J\xF4\xC0'{}\xA1\a\xAB\xD7{q\xE5\xC3@\b<`\xFFQ\xE2\xF4\xFE#\xE8=\r\xBD\x8F\xBE\\\xF9\xF0\xD1~\xF6F\xF3\x8F\x0E\x0ER}\xE1\xFD\x85\xE79\x10' p\xBC\xD0\x04\xD6\xEBS\f\xA0\x01\xF3w\x95\xF2\xEEB\x1F\x06\\P\x04\xDC\x00\xC3\xDDU\xCC]\xC5\xDAU\xEC\xDD\xC4\xE9\xC4\v\xFB\v/`\xA0\xB9\xABl\xED*\xF7v\x95\xFB\xBB\xB1>j\xE7\x90(\b\xBE\xFF8\f\xD2\xEE\x87E\xC1\xD5y\xE2\xE6\xC2MdQ\xC5\x83>\x06Rq\xAAy\xE0\x0F\x03\x02\x9F},\xA0n\x9F9\xA3\x9E\xD18\x1D\xF3\x10U\x01\xD5\xC5b\x17K\x11\xD9\x17\xFB\xBE'\xBDs6\x04\xDB\xC6 %\x94\xBD\xD1\xCB}\xFBl\xC8CU\xDC\x1F~g'\xD4\v\xDE\xD0\x9F\xB8\xA5|\x9Ab\xA9Vv\x95\xD7wY\x1D\xD3\xFAgvWn\xE1X?\xAE2\xB9\xDD}F\xEDve\xA4~\xF8\r\xAB\xC8\x03\xE4\xFB\xBE\xB4\xF6n-\xD9\x13.\xD9\xCF\x1E\x91}\x80\xAB\xB4\xB0.,q\x1DC#3\e\x1DC\xB1\x976\x84\x97\xE9\xF6\x95@\xFCm\x94D8\x85T\xC4\xDDF\x8D\x02\xA41\x7F\xE2tj\x93i\x1F4\bJn\xE2a\x17\x1C}<8\xC0\xB2\xB0\x9B.j\xF8r\xE3\x03\xB1\xC8\xA7\xE2\x89\x1E\xA6\xB3\x1E\xCA\x89\x87H\x01\x97\xDD\xA4\xF1\x90F\xBC\x882\xD4o\x9BE\x0F/\xBC\xC9A\x8E\x80\xF4\x10~\xE3\xA3\xFDp\x13s\x8E\xC0k\xD4\x13R\xA9\xEF\x84$\x84\x9E\x87\xDC\x11\x00\xC9h\x0E\x81a\x90:\x84\xFD\x87i1\xD0N\xF3\x85\xB8)\x9C|\xE3\xA3G\x89\x9E\x0F\x80\x0Fx\xCE\a\xAE\xE7\x8C\x8AB\xF0\x9F!-\x88\x92\xF0hI\xDE_\x92\xE5\x84\xB0\xBF `p\xF7\x9F\xC2\xCAO\xE3+\x1C\xC0\x05\x8D\x83\xF6\xDBn\xFBgi{)\xB0\x05:\xC8\xEEgs\vY\x9C\x16\x94/B\x9Ai\xF7\xD0\x84\x15\x98GH\x91\xDD\x16\x0ELB\xEB\xE7\xAAH.0\x00M\xC9m\xF1T4\xC5\xE3\xB6\x84\x00d\x97\x00\xAD\x894\xCC{A\xA2\x0E\xFB\xE0@\xEC;8\x80\xBF2\xFB\xB3\x0E\x0E\xA0\v\xA1\x16\x1E\xBC\xB7\vb(\xD5\xB1\x90\xC7!\x18\xBE\xBF\x94\x98Q~\x01\xEF\xEF*\xBF\bv\x9B\x81\x13\tj\x85\x13\x86\xE8a\e\x178p\e\x04=\xDF\x00\x0E_\xA0AOn\xE2\xAE|\et\x9F8\xDA\xE8\xDAE,{G\x9C\x8Dn\x10\x9C\xC2\xF1\xC2\xC4\xB3\xCA\x0E\x86<\xB4\x15j\xA4\x89h\x8F&\xA2;\xCA/\xE3\xD4`\x7F\xEFA\xEC\x15\x01&v`^\xF6J@zfe\x06\x01\xE3N7\xBF$\xF4\xC7\xF3\xCB\t\xF8\xBB\xC9\xB9\xF9\xA5\x19\xA6\x0E6\xD2\xFFs|\xC2?\n\"\x87\xFF\x16\xB9\f\x03\xFF\x13\x9B\xBB\xC9\xFC"
```

This is not something Oga can parse.

**Comment by 0mega** [comment]
Correct it's the one I used. You are right, the `#open()` itself returns some unreadable result.
Thanks for your time.
