### ISSUE TITLE
Nested Pseudo-classes

### ISSUE THREAD

**Issue by zumoshi** [YorickPeterse/oga#182]
```ruby
doc = Oga.parse_html '<div>a</div><div>b</div>'
doc.css('div:not(:nth-child(2))')
```
fails with:
```
C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/ruby-ll-2.1.2/lib/ll/driver.rb:15:in `parser_error': Unexpected T_NTH, expected T_IDENT instead (LL::ParserError)
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:270:in `block in each_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/lexer.rb:1011:in `add_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/lexer.rb:487:in `advance'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:269:in `each_token'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:293:in `parse'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:293:in `parse'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:245:in `block in parse_with_cache'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/lru.rb:79:in `block in get_or_set'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/lru.rb:122:in `synchronize'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/lru.rb:79:in `get_or_set'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/css/parser.rb:245:in `parse_with_cache'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/oga-2.11/lib/oga/xml/querying.rb:78:in `css'
        from test.rb:4:in `<main>'
```

while this is a valid css3 selector ([example](https://jsfiddle.net/Ljk96tsn/)).

**Comment by YorickPeterse** [comment]
This has been moved to https://gitlab.com/yorickpeterse/oga/issues/182
